info:
  component: Edge Server


server:
  port: 8766

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

spring.sleuth.sampler.percentage: 1.0

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'
    
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false # solo le habla a eureka pero no se registra
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    api-users:
        path: /users/v1/**
        serviceId: api-users
        stripPrefix: false
        sensitiveHeaders:

    api-posts:
        path: /posts/v1/**
        serviceId: api-posts
        stripPrefix: false
        sensitiveHeaders:
   
    api-comments:
        path: /comments/v1/**
        serviceId: api-comments
        stripPrefix: false
        sensitiveHeaders:
   
   
    api-friendships:
        path: /friendships/v1/**
        serviceId: api-friendships
        stripPrefix: false
        sensitiveHeaders:
    
    api-auth:
        path: /auth/v1/**
        serviceId: api-auth
        stripPrefix: false
        sensitiveHeaders: